travis:
  secure:
    BINSTAR_TOKEN: mGyT2A9InlP2uQoRkkK2XeixNL9i19sqX0c2JsWkfBcj9LWmaALdfwUPDEmKdR6fvrlrHrOZq9PfV13hTkqEv+hdBuDMAmWEqLvUjN53N4MQL/xcUiSLtg3vEqn1VewPFEI5vfRXVLZd1repFhclu+k5lsQNPKjXrKzC/bSEXVP82HpCEcwNJl0dkaalBoyrh203Re7zm3CX+TaGrRBmRAyrVHyEKOAQ68TJBRts1qmS9KS8s+cC7bupeCu2lAeDhOLLxiS/Wgocl39CzGIXip0EOAsoNPqX7mYlU3I4wvszmy9wRBCT8hwEr9c7C9LX0iXtQMrh+uPhIWwMOGwdvBFJJaKqxNQQkeZqa0DZeJC6A/e66BKt9y96BH3qblz6LijTLeLVzbSoungJtftq+4eriMfg37QYhhVbV/B18hAkzJEVWgvqIvxTyFkF3QkwUFwlIOOaX2VINY1J2VWi0nWdeVfcDSps2riVepayvg+PNI2FLE9V7jmTpSivG+/6IJnzwLhoWONAhyDIYKmvHpe5M2krg9JjSKIFBUiy5t1oVqPjncy+95zG0j+BCLVSXARYSPfw2J7MkTtRUdQU8NvSdtz+Sk++1bWaJaBCcrfcUldyWndKF38dQ0TxnDCuXXGm+vfBLRsYvg47HCjG3jLv+/vtrNGnfg77PTVa7b4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
